// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AHC_dissim_cpp
NumericMatrix AHC_dissim_cpp(NumericMatrix X, String method, bool dissim_matrix);
RcppExport SEXP _AHClassif_AHC_dissim_cpp(SEXP XSEXP, SEXP methodSEXP, SEXP dissim_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type dissim_matrix(dissim_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(AHC_dissim_cpp(X, method, dissim_matrix));
    return rcpp_result_gen;
END_RCPP
}
// dissim
NumericMatrix dissim(NumericMatrix X, String method, bool dissim_matrix);
RcppExport SEXP _AHClassif_dissim(SEXP XSEXP, SEXP methodSEXP, SEXP dissim_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type dissim_matrix(dissim_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(dissim(X, method, dissim_matrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AHClassif_AHC_dissim_cpp", (DL_FUNC) &_AHClassif_AHC_dissim_cpp, 3},
    {"_AHClassif_dissim", (DL_FUNC) &_AHClassif_dissim, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_AHClassif(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
