# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dissim <- function(X, method = "average", dissim_matrix = FALSE) {
    .Call('_AHClassif_dissim', PACKAGE = 'AHClassif', X, method, dissim_matrix)
}

