# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dissimilarity method using C++
#'
#' @param X Data matrix by default (if dissim_matrix = True, then this is the dissimilarity matrix)
#' @param String method type of linkage for the Lance-Williams distance ("average" by default)
#' @param dissim_matrix false by default, put true if you give the dissimilarity matrix directly
#' @return P clustering matrix (each row corresponds to each iteration)
#'
#' @useDynLib AHClassif
#' @importFrom Rcpp sourceCpp
#'
#' @export
#'
#' @examples
#' X = as.matrix(iris[-5])
#' method = "single"
#' P = AHC_dissim_cpp(X, method)
#'
AHC_dissim_cpp <- function(X, method = "average", dissim_matrix = FALSE) {
    .Call('_AHClassif_AHC_dissim_cpp', PACKAGE = 'AHClassif', X, method, dissim_matrix)
}

